## Deliverable 2. Create a Customer Travel Destinations Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [3]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_Database.csv")
city_data_df.head()

,WeatherPy_Database.csv,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Bluff,NZ,-46.6000,168.3333,60.80,76,99,9.37,overcast clouds
1,1,Camacha,PT,33.0833,-16.3333,60.22,82,20,18.41,few clouds
2,2,Mount Gambier,AU,-37.8333,140.7667,54.97,86,78,9.40,light rain
3,3,New Norfolk,AU,-42.7826,147.0587,51.30,76,100,5.01,light rain
4,4,Pevek,RU,69.7008,170.3133,30.15,90,100,0.60,overcast clouds

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 35
What is the maximum temperature you would like for your trip? 75

In [5]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,WeatherPy_Database.csv,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Bluff,NZ,-46.6000,168.3333,60.80,76,99,9.37,overcast clouds
1,1,Camacha,PT,33.0833,-16.3333,60.22,82,20,18.41,few clouds
2,2,Mount Gambier,AU,-37.8333,140.7667,54.97,86,78,9.40,light rain
3,3,New Norfolk,AU,-42.7826,147.0587,51.30,76,100,5.01,light rain
6,6,Airai,TL,-8.9266,125.4092,67.75,75,41,3.98,scattered clouds
8,8,Olafsvik,IS,64.8945,-23.7142,38.12,94,99,18.61,overcast clouds
11,11,Port Elizabeth,ZA,-33.9180,25.5701,61.32,87,0,11.50,clear sky
12,12,Muros,ES,42.7762,-9.0603,58.15,74,43,8.57,scattered clouds
13,13,Bethel,US,41.3712,-73.4140,53.91,89,100,4.61,moderate rain
18,18,Kodiak,US,57.7900,-152.4072,45.91,76,100,12.66,overcast clouds

In [6]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

WeatherPy_Database.csv    419
City                      419
Country                   415
Lat                       419
Lng                       419
Max Temp                  419
Humidity                  419
Cloudiness                419
Wind Speed                419
Current Description       419
dtype: int64

In [7]:
preferred_cities_df.isnull().sum()

WeatherPy_Database.csv    0
City                      0
Country                   4
Lat                       0
Lng                       0
Max Temp                  0
Humidity                  0
Cloudiness                0
Wind Speed                0
Current Description       0
dtype: int64

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
#dropna()
#If you have some rows with null values, you'll need to drop them using the dropna() method at the end of your filtering statement when you are creating the new DataFrame.
clean_df = preferred_cities_df.dropna()
clean_df.head(10)

,WeatherPy_Database.csv,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Bluff,NZ,-46.6000,168.3333,60.80,76,99,9.37,overcast clouds
1,1,Camacha,PT,33.0833,-16.3333,60.22,82,20,18.41,few clouds
2,2,Mount Gambier,AU,-37.8333,140.7667,54.97,86,78,9.40,light rain
3,3,New Norfolk,AU,-42.7826,147.0587,51.30,76,100,5.01,light rain
6,6,Airai,TL,-8.9266,125.4092,67.75,75,41,3.98,scattered clouds
8,8,Olafsvik,IS,64.8945,-23.7142,38.12,94,99,18.61,overcast clouds
11,11,Port Elizabeth,ZA,-33.9180,25.5701,61.32,87,0,11.50,clear sky
12,12,Muros,ES,42.7762,-9.0603,58.15,74,43,8.57,scattered clouds
13,13,Bethel,US,41.3712,-73.4140,53.91,89,100,4.61,moderate rain
18,18,Kodiak,US,57.7900,-152.4072,45.91,76,100,12.66,overcast clouds

In [9]:
clean_df.isnull().sum()

WeatherPy_Database.csv    0
City                      0
Country                   0
Lat                       0
Lng                       0
Max Temp                  0
Humidity                  0
Cloudiness                0
Wind Speed                0
Current Description       0
dtype: int64

In [10]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Bluff,NZ,60.80,overcast clouds,-46.6000,168.3333,
1,Camacha,PT,60.22,few clouds,33.0833,-16.3333,
2,Mount Gambier,AU,54.97,light rain,-37.8333,140.7667,
3,New Norfolk,AU,51.30,light rain,-42.7826,147.0587,
6,Airai,TL,67.75,scattered clouds,-8.9266,125.4092,
8,Olafsvik,IS,38.12,overcast clouds,64.8945,-23.7142,
11,Port Elizabeth,ZA,61.32,clear sky,-33.9180,25.5701,
12,Muros,ES,58.15,scattered clouds,42.7762,-9.0603,
13,Bethel,US,53.91,moderate rain,41.3712,-73.4140,
18,Kodiak,US,45.91,overcast clouds,57.7900,-152.4072,

In [17]:
# 6a. Set parameters to search for hotels with 5000 meters. (Paris)

params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
    "lat": lat,
    "lng": lng
}

# 6b. Iterate through the hotel DataFrame.
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [18]:
# 7. Drop the rows where there is no Hotel Name.
try:
    clean_hotel_df=hotel_df.dropna()
    
except:
    print('No empty rows to drop')
    clean_hotel_df=hotel_df

In [24]:
clean_hotel_df.isnull().sum()

City                   0
Country                0
Max Temp               0
Current Description    0
Lat                    0
Lng                    0
Hotel Name             0
dtype: int64

In [19]:
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Bluff,NZ,60.80,overcast clouds,-46.6000,168.3333,Bluff Homestead - Guesthouse & Campervan Park
1,Camacha,PT,60.22,few clouds,33.0833,-16.3333,Hotel Porto Santo & Spa
2,Mount Gambier,AU,54.97,light rain,-37.8333,140.7667,The Commodore
3,New Norfolk,AU,51.30,light rain,-42.7826,147.0587,The Shingles Riverside Cottages
6,Airai,TL,67.75,scattered clouds,-8.9266,125.4092,
8,Olafsvik,IS,38.12,overcast clouds,64.8945,-23.7142,Hotel Olafsvik
11,Port Elizabeth,ZA,61.32,clear sky,-33.9180,25.5701,39 On Nile Guest House
12,Muros,ES,58.15,scattered clouds,42.7762,-9.0603,Apartment Av. Castelao
13,Bethel,US,53.91,moderate rain,41.3712,-73.4140,Courtyard by Marriott Danbury
18,Kodiak,US,45.91,overcast clouds,57.7900,-152.4072,Best Western Kodiak Inn And Convention Center

In [26]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [21]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
#The text inside the multiline string is HTML code. HTML code is defined by the opening and closing the angular brackets (e.g., <tag> and <tag/>). Angular brackets always come in pairs. The opening angular bracket is followed by some text inside, such as dl, dt, and dd. The closing angular bracket is preceded by a forward-slash ("/"). The text inside with the angular brackets is called a tag. 

#Here's what these tags mean:

#The <dl> tag is a description list (dl).
#The <dt> tag is a term or name in a description list that is nested under the <dl> tag.
#The <dd> tag is used to define the term or name or <dt> tag.
#<b> Defines bold text
info_box_template = """

<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt><b>Weather</b></dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [22]:
# 11a. Add a marker layer for each city to the map. 



# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))